default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: 127.0.0.1
  port: 5432
  database: scoopy_development
  username: postgres
  password: postgres

test:
  <<: *default
  host: 127.0.0.1
  port: 5432
  database: scoopy_test
  username: postgres
  password: postgres

production:
  <<: *default
  host: <%= ENV.fetch("PGHOST") %>
  port: <%= ENV.fetch("PGPORT") %>
  database: <%= ENV.fetch("PGDATABASE") %>
  username: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>

queue:
  <<: *default
  host: <%= ENV.fetch("PGHOST") %>
  port: <%= ENV.fetch("PGPORT") %>
  database: <%= ENV.fetch("PGDATABASE") %>
  username: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>

cache:
  <<: *default
  host: <%= ENV.fetch("PGHOST") %>
  port: <%= ENV.fetch("PGPORT") %>
  database: <%= ENV.fetch("PGDATABASE") %>
  username: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>

cable:
  <<: *default
  host: <%= ENV.fetch("PGHOST") %>
  port: <%= ENV.fetch("PGPORT") %>
  database: <%= ENV.fetch("PGDATABASE") %>
  username: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>