default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "127.0.0.1") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

development:
  <<: *default
  database: scoopy_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: scoopy_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "scoopy") %>
  username: <%= ENV.fetch("PGUSER", "admin") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>

queue:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "scoopy") %>
  username: <%= ENV.fetch("PGUSER", "admin") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>

cache:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "scoopy") %>
  username: <%= ENV.fetch("PGUSER", "admin") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>

cable:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "scoopy") %>
  username: <%= ENV.fetch("PGUSER", "admin") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>