default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "127.0.0.1") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "postgres") %>

development:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "scoopy_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "scoopy_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "scoopy_production") %>

queue:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "scoopy_production") %>

cache:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "scoopy_production") %>

cable:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "scoopy_production") %>